In [ ]:
import numpy as np
a = np.random.randint(1,9, size = (3,3))
print(a)
b = np.ones([3,3])
print(b)
add_ = np.add(a,b)
sub_ = np.subtract(a,b)
print(add_)
print(sub_)


[[6 8 1]
 [4 7 2]
 [5 7 7]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7. 9. 2.]
 [5. 8. 3.]
 [6. 8. 8.]]
[[5. 7. 0.]
 [3. 6. 1.]
 [4. 6. 6.]]


In [ ]:

a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
b = np.array(a)

b[b % 2 != 0]=100
print(b)


[100   2 100   4 100   6 100   8 100  10 100  12 100  14 100]


In [ ]:
import numpy as np

a = np.array([1, 1, 2, 3, 3, 3, 4, 5, 6, 7, 7, 7, 8, 8, 9])

values, counts = np.unique(a, return_counts=True)
values = values[counts > 1] # 1 > 1 | 2 > 1 != 1 | 3 > 1 |
count = counts[counts > 1] # 1 > 1 = 2 | 3 > 1 = 3 |
print("Values :", values)
print("Count :", count)

Values : [1 3 7 8]
Count : [2 3 3 2]
