In [ ]:
import numpy as np

a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a = np.full((2,3), 7)
print(a)



[[7 7 7]
 [7 7 7]]


In [ ]:
a = np.full((2,3), 5)

print(a)
b = np.full((3,2), 9)

print(b)

[[5 5 5]
 [5 5 5]]
[[9 9]
 [9 9]
 [9 9]]


In [ ]:
a = np.random.randint(1, 10, size=(2,3))
print(a)

[[9 6 5]
 [1 4 2]]


In [ ]:
a = np.random.rand(2,3)
print(a)

[[0.99518464 0.23155322 0.83650591]
 [0.26345441 0.56935324 0.09589027]]
