In [ ]:
import numpy as np
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [ ]:
arr = np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
arr = np.ones((2, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr = np.arange(1,10,3)
print(arr)

[1 4 7]


In [ ]:
arr = np.linspace(1,4,4)
print(arr)

[1. 2. 3. 4.]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
a = arr.reshape(2,3)
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
a = np.sum(arr)
print(a)

15


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
a = np.mean(arr)
print(a)


3.5


In [ ]:
arr = np.array([10, 20, 30])
a = np.max(arr)
print(a)

30


In [ ]:
arr = np.array([10, 20, 30])
a = np.min(arr)
print(a)

10


In [ ]:
arr = np.array([10, 15])
a = np.sqrt(arr)
print(a)

[3.16227766 3.87298335]


In [ ]:
arr = np.array([50, 20, 30, 10, 40])
a = np.sort(arr)
print(a)

[10 20 30 40 50]


In [ ]:
arr = np.array([1, 2, 3])
arr1 = np.array([4, 5, 6])
a = np.concatenate((arr1,arr))
print(a)

[4 5 6 1 2 3]


In [ ]:

arr = np.array([[1,2],
                [3,4]])

arr1 = np.array([[5,6],
                 [7,8]])

a = np.dot(arr, arr1)

print(a)

[[19 22]
 [43 50]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
a = (arr.size)
print(a)

5


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
a = np.append(arr,6)
print(a)

[1 2 3 4 5 6]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
a = np.delete(a,4)
print(a)


[1 2 3 4]


In [ ]:


arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

a = np.transpose(arr)

print(a)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
a = np.add(arr,6)
print(a)

[ 7  8  9 10 11]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
a = np.subtract(arr,1)
print(a)

[0 1 2 3 4]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
a = np.multiply(arr,2)
print(a)

[ 2  4  6  8 10]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
a = np.divide(arr,2)
print(a)

[ 5. 10. 15. 20. 25.]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
a = np.log(5)
print(a)

1.6094379124341003


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
a = np.median(arr)
print(a)


4.0


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
a = np.var(arr)
print(a)


2.9166666666666665


In [ ]:
arr = np.array([50, 20, 30, 10, 40])
a = np.sort(arr)[::-1]
print(a)

[50 40 30 20 10]
